@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов to-be для контейнера Модуль взаимодействия с датчиками
LAYOUT_WITH_LEGEND()


System_Ext(h1, "Дом", "Система отопления, ворота, датчики")


Container(db, "База данных настроек", "Хранит настройки устройств", "Позволяет получать и сохранять настройки")
Component(gateway, "Взаимодействие с устройствами", "Модуль сетевого взаимодействия с устройствами")
Component(state, "Хранение состояний устройств", "Стейт-машина")
Component(sync, "Синхронизация настроек", "Актуализирует настройки устройств в соответствии с хранимым в БД")


Rel(db, sync, "Считывает настройки", "SQL")
Rel(sync, state, "Актуализирует настройки")
Rel(h1, gateway, "Взаимодействует с устройствами", "HTTPS/BIN")
Rel(state, gateway, "Получает сообщения/ Отправляет команды", "HTTPS/JSON")


@enduml
