@startuml
!include C4_Context.puml
title Диаграмма контекста as is для системы 'Тёплый дом'
top to bottom direction

System_Ext(h1, "Дом 1", "Система отопления, датчик температуры")
System_Ext(h2, "Дом 2", "Система отопления, датчик температуры")
System_Ext(h3, "Дом 3", "Система отопления, датчик температуры")


System(system, "Система 'Тёплый дом'", "Сохраняет информацию, предоставляет её пользователю")

Person(user, "Пользователь", "Пользователь системы, владелец дома, в котором установлены датчики")
Person(admin, "Администратор", "Администратор, сотрудник технической поддержки")



Rel(user, system, "Включает/выключает отопление")
Rel(system, user, "Получает информацию о температуре")
Rel(admin,system,"Создаёт датчики")
Rel(h1,system,)
Rel(h2,system,"Управляем датчиками")
Rel(h3,system,"Датчики при включении регистрируются")

@enduml
