@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Диаграмма контейнеров to-be для системы 'Тёплый дом'
top to bottom direction
LAYOUT_WITH_LEGEND()

System_Ext(h1, "Дом", "Система отопления, ворота, датчики")
Container(system, "Модуль взаимодействия с устройствами [сервис на Go]", "Получает телеметрию, отправляет команды на включение/выключение")
ContainerDb(db, "База данных настроек [postgres]", "Хранит настройки пользователей, датчиков")
ContainerDb(telemetry, "База данных телеметрии [postgres]", "Хранит показания, датчиков")
Container(logic, "Сервис обработки логики", "Обработка сообщений, генерация событий по сценариям")
Container(api, "API. Сервис взаимодействия с пользователем [сервис c#]", "Настройка датчиков, сценариев, получение показаний телеметрии и сработавших событий")
Container(front, "Сайт, SaaS решение для всех пользователей [Angular]", "Регистрация новых пользователей, подключение датчиков, мониторинг, отправка команд")
Container(mobile, "Мобильное приложение [Android, IOS]", "Получение показаний телеметрии и отправка команд")

Person(user, "Пользователь", "Пользователь системы, владелец дома, в котором установлены датчики")
'Person(admin, "Администратор", "Администратор, сотрудник технической поддержки")

Rel(system, db, "считывает созданные датчики и их настройки")
Rel(system, telemetry, "сохраняет показания датчиков")
Rel(api, db, "получение/сохранение настроек")
Rel(api, telemetry, "получение показаний датчиков")
Rel(front, api, "Получение данных")
Rel(mobile, api, "Получение данных")
Rel(user, front, "Получение данных")
Rel(user, mobile, "Получение данных")

Rel(h1,system,"подключается для передачи телеметрии и получения команд")
Rel(telemetry, logic, "считывает телеметрию")
Rel(db, logic, "считывает настройки сценариев")
Rel(logic, system, "Формирует задания на отправку команд")

@enduml
